"""
utils/pdf_exporter.py
---------------------
Generates PDF documents for RAGnition.

PDFs:
  - generate_questions_pdf()   — clean question paper with correct answers marked
  - generate_mock_paper_pdf()  — exam paper (questions only, no answers)
  - generate_mock_answerkey_pdf() — professional answer key with full explanations
"""

from fpdf import FPDF
from typing import Any

# Fixed A4 margins
L_M, R_M, T_M = 18, 18, 22


def _safe(text: str) -> str:
    """Strip/replace all non-latin-1 characters so FPDF never crashes."""
    if not text:
        return ""
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2022": "*", "\u2026": "...",
        "\u00b2": "2", "\u00b3": "3", "\u00b0": "deg",
        "\u03b1": "alpha", "\u03b2": "beta", "\u03c0": "pi",
        "\u2264": "<=", "\u2265": ">=", "\u2260": "!=",
        "\u00e9": "e", "\u00e8": "e", "\u00ea": "e",
        "\u00e0": "a", "\u00e2": "a", "\u00f4": "o",
        "\u00fb": "u", "\u00fc": "u", "\u00ef": "i",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    # Final fallback: encode to latin-1, replace anything unmatched with ?
    return text.encode("latin-1", errors="replace").decode("latin-1")


class _BasePDF(FPDF):
    """Base class with consistent margins, header, footer, and helper methods."""

    def __init__(self, title: str = "RAGnition"):
        super().__init__()
        self._doc_title = title
        self.set_margins(L_M, T_M, R_M)
        self.set_auto_page_break(auto=True, margin=20)

    @property
    def ew(self) -> float:
        """Effective usable width."""
        return self.w - L_M - R_M

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(102, 126, 234)
        self.set_x(L_M)
        self.cell(self.ew, 6, "RAGnition  |  AI Powered Exam Preparation", align="L", ln=True)
        self.set_draw_color(102, 126, 234)
        self.set_line_width(0.4)
        self.line(L_M, self.get_y(), self.w - R_M, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.set_x(L_M)
        self.cell(self.ew, 8, f"Page {self.page_no()}  |  Generated by RAGnition", align="C")

    # ── Layout helpers ────────────────────────────────────────────────────────

    def put_title(self, title: str, subtitle: str = ""):
        self.set_x(L_M)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(102, 126, 234)
        self.multi_cell(self.ew, 9, _safe(title), align="C")
        if subtitle:
            self.set_x(L_M)
            self.set_font("Helvetica", "", 10)
            self.set_text_color(100, 100, 100)
            self.multi_cell(self.ew, 6, _safe(subtitle), align="C")
        self.ln(5)
        self.set_text_color(30, 30, 30)

    def put_section(self, text: str):
        self.ln(3)
        self.set_x(L_M)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(102, 126, 234)
        self.multi_cell(self.ew, 7, _safe(text))
        self.set_draw_color(180, 180, 255)
        self.set_line_width(0.3)
        self.line(L_M, self.get_y(), self.w - R_M, self.get_y())
        self.ln(4)
        self.set_text_color(30, 30, 30)

    def put_text(self, text: str, bold: bool = False,
                 color: tuple = (30, 30, 30), size: int = 10, indent: float = 0):
        self.set_x(L_M + indent)
        self.set_font("Helvetica", "B" if bold else "", size)
        self.set_text_color(*color)
        self.multi_cell(self.ew - indent, 6, _safe(text))
        self.set_text_color(30, 30, 30)

    def put_note(self, text: str, color: tuple = (70, 70, 70), indent: float = 6):
        self.set_x(L_M + indent)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(*color)
        self.multi_cell(self.ew - indent, 5, _safe(text))
        self.set_text_color(30, 30, 30)

    def put_hr(self):
        self.set_draw_color(220, 220, 220)
        self.set_line_width(0.3)
        self.line(L_M, self.get_y(), self.w - R_M, self.get_y())
        self.ln(4)


# ═══════════════════════════════════════════════════════════════════════════════
# MCQ / True-False / All Types — Clean Question Paper with Answers
# ═══════════════════════════════════════════════════════════════════════════════

def generate_questions_pdf(
    questions: list[dict[str, Any]],
    question_type: str,
    difficulty: str,
) -> bytes:
    """
    Clean question paper PDF with correct answers marked.
    Shows: Question, Options (with correct one highlighted), Answer, Explanation.
    Does NOT include user's quiz answers — this is a study document.
    """
    pdf = _BasePDF()
    pdf.add_page()
    pdf.put_title(
        f"{question_type} Questions",
        f"Difficulty: {difficulty}  |  {len(questions)} Question(s)"
    )

    for i, q in enumerate(questions):
        correct  = str(q.get("answer", "")).strip()
        expl     = q.get("explanation", "")
        options  = q.get("options") or []

        # Question
        pdf.put_text(f"Q{i + 1}. {q.get('question', '')}", bold=True)
        pdf.ln(1)

        if options:
            for opt in options:
                opt_s = str(opt).strip()
                # Check if this option is the correct answer
                is_correct_opt = (
                    opt_s[:2].upper() == correct[:2].upper()
                    or correct.upper() in opt_s.upper()
                    or opt_s.upper() == correct.upper()
                )
                if is_correct_opt:
                    pdf.set_x(L_M + 6)
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.set_text_color(0, 130, 0)
                    pdf.multi_cell(pdf.ew - 6, 6, f"* {_safe(opt_s)}  [CORRECT]")
                    pdf.set_text_color(30, 30, 30)
                else:
                    pdf.put_text(f"   {opt_s}", indent=6, color=(70, 70, 70))
        else:
            # Short / Long / Case — just show the answer
            pdf.set_x(L_M + 6)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(0, 130, 0)
            pdf.multi_cell(pdf.ew - 6, 6, f"Answer: {_safe(correct)}")
            pdf.set_text_color(30, 30, 30)

        if expl:
            pdf.ln(1)
            pdf.put_note(f"Explanation: {expl}", color=(60, 60, 60))

        pdf.ln(4)
        pdf.put_hr()

    return bytes(pdf.output())


# ═══════════════════════════════════════════════════════════════════════════════
# MCQ Interactive Quiz Result PDF
# ═══════════════════════════════════════════════════════════════════════════════

def generate_quiz_result_pdf(
    questions: list[dict[str, Any]],
    user_answers: dict[int, str],
    score: int,
    total: int,
) -> bytes:
    """
    Quiz result PDF showing: correct answer, whether user was right/wrong, explanation.
    Used after submitting MCQ / True-False quiz.
    """
    pdf = _BasePDF()
    pdf.add_page()
    pct = int(score / total * 100) if total else 0
    pdf.put_title("Quiz Results", f"Score: {score} / {total}  ({pct}%)")

    for i, q in enumerate(questions):
        correct  = str(q.get("answer", "")).strip()
        expl     = q.get("explanation", "")
        options  = q.get("options") or []
        user_sel = str(user_answers.get(i, "")).strip()

        is_correct = (
            user_sel[:2].upper() == correct[:2].upper()
            or correct.lower() in user_sel.lower()
        )

        pdf.put_text(f"Q{i + 1}. {q.get('question', '')}", bold=True)
        pdf.ln(1)

        for opt in options:
            opt_s = str(opt).strip()
            is_opt_ans  = (opt_s[:2].upper() == correct[:2].upper()
                           or correct.upper() in opt_s.upper()
                           or opt_s.upper() == correct.upper())
            is_opt_user = (opt_s == user_sel)

            pdf.set_x(L_M + 6)
            if is_opt_ans:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(0, 130, 0)
                pdf.multi_cell(pdf.ew - 6, 6, f"[CORRECT] {_safe(opt_s)}")
            elif is_opt_user and not is_opt_ans:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(180, 0, 0)
                pdf.multi_cell(pdf.ew - 6, 6, f"[YOUR ANSWER - WRONG] {_safe(opt_s)}")
            else:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(pdf.ew - 6, 6, f"   {_safe(opt_s)}")
            pdf.set_text_color(30, 30, 30)

        pdf.ln(2)
        # Result badge (cell only — no multi_cell, safe for single line)
        pdf.set_x(L_M)
        if is_correct:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_fill_color(220, 255, 220)
            pdf.set_text_color(0, 120, 0)
            pdf.cell(pdf.ew, 7, "  CORRECT", ln=True, fill=True)
        else:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_fill_color(255, 220, 220)
            pdf.set_text_color(160, 0, 0)
            label = f"  INCORRECT  |  Correct: {_safe(correct[:60])}"
            pdf.cell(pdf.ew, 7, label, ln=True, fill=True)

        if expl:
            pdf.ln(1)
            pdf.put_note(f"Explanation: {expl}", color=(60, 60, 60))

        pdf.set_text_color(30, 30, 30)
        pdf.ln(4)
        pdf.put_hr()

    return bytes(pdf.output())


# ═══════════════════════════════════════════════════════════════════════════════
# Mock Test — Paper PDF
# ═══════════════════════════════════════════════════════════════════════════════

def generate_mock_paper_pdf(exam: dict[str, Any]) -> bytes:
    """Clean exam paper PDF — questions only, no answers."""
    pdf = _BasePDF()
    pdf.add_page()
    pdf.put_title(
        exam.get("title", "Mock Examination Paper"),
        f"Total Marks: {exam.get('total_marks', 0)}"
    )

    section_letter = "A"
    for section in exam.get("sections", []):
        q_type     = section["type"]
        marks_each = section["marks_each"]
        sec_total  = section["total_marks"]

        pdf.put_section(
            f"SECTION {section_letter} — {q_type.upper()}  "
            f"[{marks_each} mark(s) each | Section Total: {sec_total} marks]"
        )

        for i, q in enumerate(section.get("questions", []), 1):
            pdf.put_text(f"Q{i}. {q.get('question', '')}", bold=True)
            for opt in (q.get("options") or []):
                pdf.put_text(f"     {opt}", indent=6, color=(60, 60, 60))
            pdf.ln(4)

        pdf.ln(3)
        section_letter = chr(ord(section_letter) + 1)

    return bytes(pdf.output())


# ═══════════════════════════════════════════════════════════════════════════════
# Mock Test — Answer Key PDF
# ═══════════════════════════════════════════════════════════════════════════════

def generate_mock_answerkey_pdf(exam: dict[str, Any]) -> bytes:
    """Professional answer key PDF with full explanations per question."""
    pdf = _BasePDF()
    pdf.add_page()
    pdf.put_title("Answer Key", exam.get("title", "Mock Examination Paper"))

    section_letter = "A"
    for section in exam.get("sections", []):
        q_type     = section["type"]
        marks_each = section["marks_each"]

        pdf.put_section(
            f"SECTION {section_letter} — {q_type}  [{marks_each} mark(s) each]"
        )

        for i, q in enumerate(section.get("questions", []), 1):
            # Question
            pdf.set_x(L_M)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 80)
            pdf.multi_cell(pdf.ew, 6, f"Q{i}. {_safe(q.get('question', ''))}")
            pdf.ln(1)

            # Answer
            pdf.set_x(L_M)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(0, 128, 0)
            pdf.multi_cell(pdf.ew, 6, f"Answer: {_safe(q.get('answer', 'N/A'))}")

            # Explanation
            expl = q.get("explanation", "")
            if expl:
                pdf.set_x(L_M)
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(60, 60, 60)
                pdf.multi_cell(pdf.ew, 5, f"Explanation: {_safe(expl)}")

            pdf.set_text_color(30, 30, 30)
            pdf.ln(4)
            pdf.put_hr()

        section_letter = chr(ord(section_letter) + 1)

    return bytes(pdf.output())
