"""
utils/pdf_exporter.py
---------------------
PDF generation for RAGnition.

All multi_cell / cell calls explicitly set X=L_M and use pdf.ew for width
to prevent the "Not enough horizontal space" FPDF exception.

MCQ options format: dict {A: str, B: str, C: str, D: str}
MCQ correct answer:  single letter string "A" | "B" | "C" | "D"
"""

from fpdf import FPDF
from typing import Any

L_M, R_M, T_M = 18, 18, 22


def _safe(text: str) -> str:
    if not text:
        return ""
    table = {
        "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2022": "*", "\u2026": "...",
        "\u00b2": "2", "\u00b3": "3", "\u00b0": "deg",
        "\u03b1": "alpha", "\u03b2": "beta", "\u03c0": "pi",
        "\u2264": "<=", "\u2265": ">=", "\u2260": "!=",
        "\u00e9": "e", "\u00e8": "e", "\u00ea": "e",
        "\u00e0": "a", "\u00e2": "a", "\u00f4": "o",
        "\u00fb": "u", "\u00fc": "u", "\u00ef": "i",
    }
    for k, v in table.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _opts_list(opts: Any) -> list[tuple[str, str]]:
    """Normalise options to [(letter, text), ...] pairs."""
    if isinstance(opts, dict):
        return [(str(k).upper(), str(v)) for k, v in sorted(opts.items())]
    if isinstance(opts, list):
        letters = ["A", "B", "C", "D"]
        result  = []
        for i, opt in enumerate(opts):
            text = str(opt).strip()
            if len(text) >= 2 and text[0].upper() in letters and text[1] in (".", ":"):
                result.append((text[0].upper(), text[2:].strip()))
            else:
                result.append((letters[i] if i < 4 else str(i), text))
        return result
    return []


def _answer_of(q: dict) -> str:
    """Return the answer for any question type (MCQ uses correct_answer)."""
    return str(q.get("correct_answer") or q.get("answer") or "N/A").strip()


class _PDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_margins(L_M, T_M, R_M)
        self.set_auto_page_break(auto=True, margin=20)

    @property
    def ew(self) -> float:
        return self.w - L_M - R_M

    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(102, 126, 234)
        self.set_x(L_M)
        self.cell(self.ew, 6, "RAGnition  |  AI Powered Exam Preparation", align="L", ln=True)
        self.set_draw_color(102, 126, 234)
        self.set_line_width(0.5)
        self.line(L_M, self.get_y(), self.w - R_M, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.set_x(L_M)
        self.cell(self.ew, 8, f"Page {self.page_no()}  |  Generated by RAGnition", align="C")

    # ── Layout helpers ──────────────────────────────────────────────────────────

    def title_block(self, title: str, subtitle: str = ""):
        self.set_x(L_M)
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(102, 126, 234)
        self.multi_cell(self.ew, 10, _safe(title), align="C")
        if subtitle:
            self.set_x(L_M)
            self.set_font("Helvetica", "", 11)
            self.set_text_color(100, 100, 100)
            self.multi_cell(self.ew, 7, _safe(subtitle), align="C")
        self.ln(6)
        self.set_text_color(30, 30, 30)

    def section_header(self, text: str):
        self.ln(4)
        self.set_x(L_M)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(102, 126, 234)
        self.multi_cell(self.ew, 8, _safe(text))
        y = self.get_y()
        self.set_draw_color(180, 160, 255)
        self.set_line_width(0.4)
        self.line(L_M, y, self.w - R_M, y)
        self.ln(4)
        self.set_text_color(30, 30, 30)

    def body(self, text: str, bold: bool = False, color=(30, 30, 30), size=10):
        self.set_x(L_M)
        self.set_font("Helvetica", "B" if bold else "", size)
        self.set_text_color(*color)
        self.multi_cell(self.ew, 6, _safe(text))
        self.set_text_color(30, 30, 30)

    def indent(self, text: str, pad: float = 8, bold: bool = False,
               color=(60, 60, 60), size=10):
        self.set_x(L_M + pad)
        self.set_font("Helvetica", "B" if bold else "", size)
        self.set_text_color(*color)
        self.multi_cell(self.ew - pad, 6, _safe(text))
        self.set_text_color(30, 30, 30)

    def hr(self, color=(210, 210, 210)):
        self.set_draw_color(*color)
        self.set_line_width(0.25)
        self.line(L_M, self.get_y(), self.w - R_M, self.get_y())
        self.ln(5)

    def fill_row(self, text: str, fill_color=(220, 255, 220), text_color=(0, 110, 0)):
        self.set_x(L_M)
        self.set_font("Helvetica", "B", 10)
        self.set_fill_color(*fill_color)
        self.set_text_color(*text_color)
        self.cell(self.ew, 8, _safe(text)[:100], ln=True, fill=True)
        self.set_text_color(30, 30, 30)


# ═══════════════════════════════════════════════════════════════════════════════
# 1. Clean Question Paper PDF (correct answer marked, no user data)
# ═══════════════════════════════════════════════════════════════════════════════

def generate_questions_pdf(
    questions: list[dict[str, Any]],
    question_type: str,
    difficulty: str,
) -> bytes:
    pdf = _PDF()
    pdf.add_page()
    pdf.title_block(
        f"{question_type} Questions",
        f"Difficulty: {difficulty}   •   {len(questions)} Question(s)"
    )

    for i, q in enumerate(questions):
        correct = str(q.get("correct_answer", q.get("answer", ""))).strip().upper()
        opts    = _opts_list(q.get("options"))
        expl    = q.get("explanation", "")

        pdf.body(f"Q{i+1}. {q.get('question','')}", bold=True)
        pdf.ln(2)

        if opts:
            for letter, text in opts:
                is_ans = letter == correct[:1]
                if is_ans:
                    pdf.set_x(L_M + 8)
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.set_text_color(0, 130, 0)
                    pdf.multi_cell(pdf.ew - 8, 7, f"* {letter}. {_safe(text)}  [CORRECT]")
                    pdf.set_text_color(30, 30, 30)
                else:
                    pdf.indent(f"   {letter}. {text}", color=(70, 70, 70))
        else:
            pdf.indent(f"Answer: {correct}", color=(0, 130, 0), bold=True)

        if expl:
            pdf.ln(1)
            pdf.set_x(L_M + 8)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.multi_cell(pdf.ew - 8, 5, f"Explanation: {_safe(expl)}")
            pdf.set_text_color(30, 30, 30)

        pdf.ln(4)
        pdf.hr()

    return bytes(pdf.output())


# ═══════════════════════════════════════════════════════════════════════════════
# 2. Quiz Result PDF (with user answers)
# ═══════════════════════════════════════════════════════════════════════════════

def generate_quiz_result_pdf(
    questions: list[dict[str, Any]],
    user_answers: dict[int, str],
    score: int,
    total: int,
) -> bytes:
    pdf = _PDF()
    pdf.add_page()
    pct = int(score / total * 100) if total else 0
    pdf.title_block("Quiz Results", f"Score: {score} / {total}   ({pct}%)")

    for i, q in enumerate(questions):
        correct    = str(q.get("correct_answer", q.get("answer",""))).strip().upper()
        opts       = _opts_list(q.get("options"))
        user_letter = str(user_answers.get(i, "")).strip().upper()[:1]
        is_correct = (user_letter == correct[:1])
        expl       = q.get("explanation", "")

        pdf.body(f"Q{i+1}. {q.get('question','')}", bold=True)
        pdf.ln(1)

        for letter, text in opts:
            is_ans  = (letter == correct[:1])
            is_user = (letter == user_letter)
            pdf.set_x(L_M + 8)
            if is_ans:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(0, 130, 0)
                pdf.multi_cell(pdf.ew - 8, 7, f"[CORRECT] {letter}. {_safe(text)}")
            elif is_user and not is_ans:
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(180, 0, 0)
                pdf.multi_cell(pdf.ew - 8, 7, f"[YOUR ANSWER - WRONG] {letter}. {_safe(text)}")
            else:
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(pdf.ew - 8, 7, f"   {letter}. {_safe(text)}")
            pdf.set_text_color(30, 30, 30)

        pdf.ln(2)
        if is_correct:
            pdf.fill_row("  CORRECT", fill_color=(220, 255, 220), text_color=(0, 110, 0))
        else:
            pdf.fill_row(f"  INCORRECT  |  Correct: {correct[:1]}", fill_color=(255, 220, 220), text_color=(150, 0, 0))

        if expl:
            pdf.ln(1)
            pdf.set_x(L_M + 8)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(pdf.ew - 8, 5, f"Explanation: {_safe(expl)}")
            pdf.set_text_color(30, 30, 30)

        pdf.ln(4)
        pdf.hr()

    return bytes(pdf.output())


# ═══════════════════════════════════════════════════════════════════════════════
# 3. Mock Test Paper PDF — questions only, no answers
# ═══════════════════════════════════════════════════════════════════════════════

def generate_mock_paper_pdf(exam: dict[str, Any]) -> bytes:
    pdf = _PDF()
    pdf.add_page()
    pdf.title_block(
        exam.get("title", "Mock Examination Paper"),
        f"Total Marks: {exam.get('total_marks', 0)}"
    )

    section_letter = "A"
    for section in exam.get("sections", []):
        q_type     = section["type"]
        marks_each = section["marks_each"]
        sec_total  = section["total_marks"]

        pdf.section_header(
            f"SECTION {section_letter}  —  {q_type.upper()}"
            f"   [{marks_each} mark(s) each  |  Section Total: {sec_total} marks]"
        )

        for i, q in enumerate(section.get("questions", []), 1):
            pdf.body(f"Q{i}. {q.get('question','')}", bold=True)
            pdf.ln(2)
            for letter, text in _opts_list(q.get("options")):
                pdf.indent(f"   {letter}. {text}", color=(60, 60, 60))
            pdf.ln(5)

        pdf.ln(3)
        section_letter = chr(ord(section_letter) + 1)

    return bytes(pdf.output())


# ═══════════════════════════════════════════════════════════════════════════════
# 4. Mock Test Answer Key PDF — full explanations
# ═══════════════════════════════════════════════════════════════════════════════

def generate_mock_answerkey_pdf(exam: dict[str, Any]) -> bytes:
    pdf = _PDF()
    pdf.add_page()
    pdf.title_block("Answer Key", exam.get("title", "Mock Examination Paper"))

    section_letter = "A"
    for section in exam.get("sections", []):
        q_type     = section["type"]
        marks_each = section["marks_each"]

        pdf.section_header(
            f"SECTION {section_letter}  —  {q_type}   [{marks_each} mark(s) each]"
        )

        for i, q in enumerate(section.get("questions", []), 1):
            answer = _answer_of(q)
            expl   = q.get("explanation", "")

            pdf.body(f"Q{i}. {q.get('question','')}", bold=True, color=(30, 30, 80))
            pdf.ln(1)
            pdf.indent(f"Answer: {answer}", color=(0, 120, 0), bold=True)
            if expl:
                pdf.set_x(L_M + 8)
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(60, 60, 60)
                pdf.multi_cell(pdf.ew - 8, 5, f"Explanation: {_safe(expl)}")
                pdf.set_text_color(30, 30, 30)

            pdf.ln(4)
            pdf.hr()

        section_letter = chr(ord(section_letter) + 1)

    return bytes(pdf.output())
